# Generated by Django 5.1.2 on 2024-10-11 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='no description', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary', models.FloatField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('detectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='api_detectors.detector')),
            ],
        ),
    ]
